// Mocks generated by Mockito 5.4.4 from annotations
// in app_test_with_backend/test/article_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes

import 'dart:async' as _i3;

import 'package:app_test_with_backend/features/news/data/datasource/interfaces/local_article_data_source.dart'
    as _i6;
import 'package:app_test_with_backend/features/news/data/datasource/interfaces/remote_article_data_source.dart'
    as _i2;
import 'package:app_test_with_backend/features/news/data/models/ArticleLocalModel.dart'
    as _i7;
import 'package:app_test_with_backend/features/news/data/models/ArticleModel.dart'
    as _i4;
import 'package:app_test_with_backend/features/news/data/models/SourceLocalModel.dart'
    as _i8;
import 'package:app_test_with_backend/features/news/data/models/SourceModel.dart'
    as _i5;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [RemoteArticleDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockRemoteArticleDataSource extends _i1.Mock
    implements _i2.RemoteArticleDataSource {
  MockRemoteArticleDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.ArticleModel>> findTopHeadlines(
    String? search,
    String? country,
    int? page,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #findTopHeadlines,
          [
            search,
            country,
            page,
          ],
        ),
        returnValue:
            _i3.Future<List<_i4.ArticleModel>>.value(<_i4.ArticleModel>[]),
      ) as _i3.Future<List<_i4.ArticleModel>>);

  @override
  _i3.Future<List<_i4.ArticleModel>> findAll(
    String? search,
    String? country,
    int? page,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #findAll,
          [
            search,
            country,
            page,
          ],
        ),
        returnValue:
            _i3.Future<List<_i4.ArticleModel>>.value(<_i4.ArticleModel>[]),
      ) as _i3.Future<List<_i4.ArticleModel>>);

  @override
  _i3.Future<List<_i5.SourceModel>> findSources(
    String? country,
    int? page,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #findSources,
          [
            country,
            page,
          ],
        ),
        returnValue:
            _i3.Future<List<_i5.SourceModel>>.value(<_i5.SourceModel>[]),
      ) as _i3.Future<List<_i5.SourceModel>>);
}

/// A class which mocks [LocalArticleDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocalArticleDataSource extends _i1.Mock
    implements _i6.LocalArticleDataSource {
  MockLocalArticleDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i7.ArticleLocalModel>> findTopHeadlines(
    String? search,
    String? country,
    int? page,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #findTopHeadlines,
          [
            search,
            country,
            page,
          ],
        ),
        returnValue: _i3.Future<List<_i7.ArticleLocalModel>>.value(
            <_i7.ArticleLocalModel>[]),
      ) as _i3.Future<List<_i7.ArticleLocalModel>>);

  @override
  _i3.Future<void> createTopHeadlines(List<_i7.ArticleLocalModel>? articles) =>
      (super.noSuchMethod(
        Invocation.method(
          #createTopHeadlines,
          [articles],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<List<_i7.ArticleLocalModel>> findAll(
    String? search,
    String? country,
    int? page,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #findAll,
          [
            search,
            country,
            page,
          ],
        ),
        returnValue: _i3.Future<List<_i7.ArticleLocalModel>>.value(
            <_i7.ArticleLocalModel>[]),
      ) as _i3.Future<List<_i7.ArticleLocalModel>>);

  @override
  _i3.Future<void> clearArticles() => (super.noSuchMethod(
        Invocation.method(
          #clearArticles,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> createAll(List<_i7.ArticleLocalModel>? articles) =>
      (super.noSuchMethod(
        Invocation.method(
          #createAll,
          [articles],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> createSources(List<_i8.SourceLocalModel>? sources) =>
      (super.noSuchMethod(
        Invocation.method(
          #createSources,
          [sources],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<List<_i8.SourceLocalModel>> findSources() => (super.noSuchMethod(
        Invocation.method(
          #findSources,
          [],
        ),
        returnValue: _i3.Future<List<_i8.SourceLocalModel>>.value(
            <_i8.SourceLocalModel>[]),
      ) as _i3.Future<List<_i8.SourceLocalModel>>);
}
