// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDd8CUREGwXJQTt2ZvycgCztY2HtMzOWsE',
    appId: '1:1061165431728:web:526fa753b7696384113475',
    messagingSenderId: '1061165431728',
    projectId: 'kdrflutter',
    authDomain: 'kdrflutter.firebaseapp.com',
    storageBucket: 'kdrflutter.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHcVW7lPgwNiTUAC2atjh1L_3aHXlXw5E',
    appId: '1:1061165431728:android:16a3930f61c639be113475',
    messagingSenderId: '1061165431728',
    projectId: 'kdrflutter',
    storageBucket: 'kdrflutter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9j1POop28dCcZpBDjNG-whr3Nf5Uzv5c',
    appId: '1:1061165431728:ios:5c642e7bf8e7cb70113475',
    messagingSenderId: '1061165431728',
    projectId: 'kdrflutter',
    storageBucket: 'kdrflutter.firebasestorage.app',
    iosBundleId: 'com.example.appTestWithBackend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9j1POop28dCcZpBDjNG-whr3Nf5Uzv5c',
    appId: '1:1061165431728:ios:5c642e7bf8e7cb70113475',
    messagingSenderId: '1061165431728',
    projectId: 'kdrflutter',
    storageBucket: 'kdrflutter.firebasestorage.app',
    iosBundleId: 'com.example.appTestWithBackend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDd8CUREGwXJQTt2ZvycgCztY2HtMzOWsE',
    appId: '1:1061165431728:web:3277b6c823fe7a89113475',
    messagingSenderId: '1061165431728',
    projectId: 'kdrflutter',
    authDomain: 'kdrflutter.firebaseapp.com',
    storageBucket: 'kdrflutter.firebasestorage.app',
  );
}
